### ISSUE TITLE
[BUG] Article scraping is too case sensitive

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#102]
### What bug did you encounter?

When cross checking sites scraped and the returned articles, it can be seen that articles containing "energy" are returned, but not "Energy" so we miss out on quite a few.

### What did you expect to happen?

A non-case-sensitive search

### Additional information

The search is performed by cheerio in the file `./src/utils/getDataFromCheerio.js`

Check the [documentation for cheerio](https://[cheerio](https://cheerio.js.org/).js.org/) to see if we can make it case insensitive.

**Comment by MizouziE** [comment]
Of course we could cheat and just add capitalized versions of the keywords...

But only if there isn't a more elegant solution. 😉

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
Now, What should I do?

**Comment by MizouziE** [comment]
@KetanParmar07 This one is about research and discovery. 

- Reproduce the bug and experiment with it to see what differences there are. 
- Read the documentation referenced in the comments above to see if something already exists to solve our problem. 
- If not, try to create a solution. 
- Research a little about regular expression searches as I think there may be a solution in understanding them well. 

Good luck, and feel free to ask questions and discuss your ideas in this thread.

**Comment by KetanParmar07** [comment]
hello, sir in which file to add solution??

**Comment by MizouziE** [comment]
> hello, sir in which file to add solution??

Wherever you think it needs to go. I would start by looking in `src/utils/getDataFromCheerio.js` to understand how the function makes use of the cheerio library to scrape the news sites using the list of keywords.

Look through the files and see how it all links up and decide where you think is best to intersect, if needs be.

**Comment by MizouziE** [comment]
Hi @KetanParmar07 have there been any developments on this, I can't find a PR for it?

**Comment by TeaBizzy** [comment]
Not sure if @KetanParmar07 is still working on this, but I took a look myself, scrubbing the cheerio docs I can't find anything that allows for case insensitive selector searches.

In my limited understanding we have 2 options:
1.  Add an extra loop that capitalizes the "e" in each energy keyword passes the new keyword through cheerio.
2. Since there isn't a lot of keywords, just add the capitalized variants.

One question however about the keywords, aren't keywords that contain "energy" + "bill" or "tax" redundant since the keyword "energy" will be found within the element anyways?

**Comment by TeaBizzy** [comment]
I ran a couple test just now where I removed the keywords that contained "energy", and instead used "energy". It appears to be giving the same results. I would speculate the best solution would be to just add "Energy" as a keyword instead of complicating the code.

@MizouziE let me know your thoughts on my speculation of redundant keywords. If they are indeed redundant should we remove them in this issue or create a new one?

**Comment by MizouziE** [comment]
@TeaBizzy You are absolutely right! Looking back I think I was getting results that included things like "high energy breakfast" or something not really pertaining to the desired subject so I was trying to weed out results like that and didn't even use "energy" on it's own.

It seems things have changed as energy has become a more and more popular topic, so may I suggest commenting out the _now_ redundant filter search pairs and also go ahead and whack Energy with a big E in the list. It seems to work just great and nearly doubles the number of articles returned.

Something along these lines...
![image](https://user-images.githubusercontent.com/90829439/192120284-444f4714-f6b1-4740-bc9f-3d6b07e28f9a.png)

Also, as this is a month stale, I'll assign it to you now.

Thanks for the investigation!

**Comment by TeaBizzy** [comment]
Ahhh, I didn't think about scenarios where energy could be associated with a food article.

I still think the easiest solution would be to just add keywords with a capital E as opposed to writing custom logic. I will make the changes tomorrow so we can close this issue. 😁
