### ISSUE TITLE
Test: Add a test suite for `paginate.js` file

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#155]
### What would you like to share?

Add a test suite for the `src/utils/paginate.js` file.
### Steps:
- Add a new file `paginate.test.js` inside `/__tests__/unit-tests`
- Add test suite for all possible scenarios

@MuminAhmadKhan  Maybe this one's yours.

**Comment by MizouziE** [comment]
> @MuminAhmadKhan Maybe this one's yours.

Let me know if you want it and I'll assign you sir :+1:

**Comment by MuminAhmadKhan** [comment]
Please assign me sir @MizouziE

**Comment by sanyamgandhak** [comment]
Hi there , Please assign to me

**Comment by MizouziE** [comment]
> Hi there , Please assign to me

Hi @sanyamgandhak , this issue is currently assigned to @MuminAhmadKhan , so it can only be re-assigned if they offer to step down or fail to respond after a long time.

Assuming that they'd like to finish this, I'd invite you to take a look through our issues as there are a number of very similar issues at the moment that we'd be very grateful for your contribution with.

Thanks for taking an interest in the project!

**Comment by MizouziE** [comment]
@MuminAhmadKhan I'd say to keep the tests just to the paginate function. Test things like:

- If called, is the output as expected.
- If number of articles is less than `limit` then there should not be a `next:` link
- The data displaying the article count and page count etc is giving accurate readings

Use the `__mocks__` folder and create all the dummy response data you need to test out the edge cases.

Let me know if that doesn't answer your question.
