### ISSUE TITLE
heroku link is not working 

### ISSUE THREAD

**Issue by rupali-codes** [Energy-Price-News-API/energy-prices-api#166]
### What would you like to share?

This **https://energy-price-news-api.herokuapp.com/** has stopped working, kindly update it.

**Comment by MizouziE** [comment]
Hi @rupali-codes , thanks for reporting. It is true that sometimes heroku closes the application down (puts it to sleep) because it is on one of their soon to expire free dynos. 

This is an issue I am working on and need to hurry up and sort out. I'll be moving it over to private hosting that won't ever close down and the API will run indefinitely. 

At the moment, if you see this:![image](https://user-images.githubusercontent.com/90829439/193402211-9c58adcb-8425-4657-94f1-1b0d75ee25ce.png)

Please just wait 10-15 seconds and hit refresh and then it should load normally:![image](https://user-images.githubusercontent.com/90829439/193402231-6b6bfbd4-b4f4-4c56-8378-29392fb22758.png)

It is very annoying that it does this, but it was the only place I could host a Node.js app for free when I started it. I'll assign this issue to myself to remind me to hurry up and get it migrated!

**Comment by leonlafa** [comment]
@MizouziE let me know if you need any support getting this live.  I have time this morning to sort this out for you.

**Comment by rupali-codes** [comment]
Since heroku shutting down their free services, I think vercel would be more better.

**Comment by MizouziE** [comment]
Appreciate it @leonlafa , but I have a solution in the pipeline. Unfortunately it has to take a backseat to ongoing work projects right now. 

@rupali-codes I agree that vercel is a better option than heroku, but where I plan to host this in the future will allow even more control over it.

I will need some help from a colleague when he and I have time, but I gotta get work done before I can concentrate on this.

@madalinignisca :wave:

**Comment by madalinignisca** [comment]
I'll hook you in.

**Comment by MizouziE** [comment]
@all-contributors add @rupali-codes for bug reporting

**Comment by MizouziE** [comment]
@all-contributos add @madalinignisca for infra and mentoring

**Comment by MizouziE** [comment]
@all-contributors add @madalinignisca for infra and mentoring
